### ISSUE TITLE
Differences to HTM

### ISSUE THREAD

**Issue by PeteSolid** [proteriax/jsx-dom#18]
Hi, thank you for the Code. I want to understand it better by asking this question:
What are the differences to https://github.com/developit/htm if I would use either with webpack?

For me, it looks like both support inline events and JSX-DOM looks more attractive because I can write the Elements without Template Literals (so better support with my IDE). But what about performance etc?

**Comment by Grafikart** [comment]
HTM does a different thing.
It will convert a template literal into a jsx element and will call a createElement() function on it. You'll need an implementation of this createElement to render something out.

You could use jsx-dom h() function to render htm template into a dom element. 
But you can use htm output with preact to create preact element
