### ISSUE TITLE
Cannot use svg import in TypeScript

### ISSUE THREAD

**Issue by elclanrs** [proteriax/jsx-dom#24]
First I tried the following as per documentation:

```typescript
import { h } from 'jsx-dom/svg';
```
but I get:

> Cannot find module 'jsx-dom/svg'

Then I tried:

```typescript
import { h } from 'jsx-dom/lib/svg';
```

but I get:

>jsx-dom/lib/svg.d.ts is not a module

That last import should work by looking at the code, but there are no emitted types for it, so I tried to omit the error:

```typescript
// @ts-ignore
import { h } from 'jsx-dom/lib/svg';
```

but then I get other type errors related to the JSX tags.

I'm not too familiar with how the build works, but there seems to be no .d.ts output.

Would you consider making the SVG code part of the main build instead of having two separate packages? It seems like that would make the library easier to use and emit the types while not increasing the size of the package by too much (~4KB from what I can tell).

**Comment by proteriax** [comment]
It is now the main build.
