### ISSUE TITLE
How to get correct height and width with ref?

### ISSUE THREAD

**Issue by elclanrs** [proteriax/jsx-dom#26]
Given:

```jsx
<div ref={div => {
  console.log(div.clientWidth);
  console.log(div.clientHeight);
}}>
  Text
</div>
```

Both width and height report `0`.

I understand why this is happening by looking at the code, because the ref callback is triggered after the element is created and appended to the parent, but not necessarily when the element is present in the DOM.

Any ideas how to fix or workaround this issue?

**Comment by proteriax** [comment]
Wrap it with a `requestAnimationFrame`?

**Comment by elclanrs** [comment]
Thank you, I got it working.
