### ISSUE TITLE
How to declare a custom element JSX type?

### ISSUE THREAD

**Issue by elclanrs** [proteriax/jsx-dom#27]
I need to get a web component typed. I started with the following:

```typescript
declare namespace JSX {
  interface IntrinsicElements {
    'my-hello-world': any;
  }
}
```

This works, but typing as `any` is not great. Ideally I'd like to type it like in jsx-dom:

```typescript
'my-hello-world': DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>
```

But none of those interfaces I need are exported.

Is there any alternative?

**Comment by proteriax** [comment]
These two types are now exported.
