### ISSUE TITLE
Tree shaking doesn't work

### ISSUE THREAD

**Issue by shoonia** [proteriax/jsx-dom#28]
Hey! Thank you so much for the library I love it, it very helpful!

I updated my `jsx-dom` dependency `6.4.13` to `6.4.17` And I see my bundle up to little bit heavy. I searched to https://bundlephobia.com/result?p=jsx-dom@6.4.17 and see the size change

I'm don't use the SVG but in my build has SVG code. I use the Parcel bundler and I add the alias to `package.json`

```json
"alias": {
    "jsx-dom": "./node_modules/jsx-dom/lib/min.js"
}
```

And this way I have a bundle is smaller. Before 78.02 KB and with the alias, it is 76.09 KB 

Is it possible to set up tree shaking as it was in 6.4.13 version?

**Comment by proteriax** [comment]
Yes, if you import from `jsx-dom/min` instead of `jsx-dom`.
