### ISSUE TITLE
Does not render <template> content

### ISSUE THREAD

**Issue by jellymann** [proteriax/jsx-dom#30]
I'm trying to create `template` elements in JSX, but none of my `template` elements have any content when I run my code.

Here is an example replicating the issue:

```jsx
let template = <template><div></div></template>
console.log(template.outerHTML)
```

Outputs the following:

```html
<template></template>
```

Expected output:

```html
<template><div></div></template>
```

**Comment by jellymann** [comment]
I have proposed my own solution to this here: #31

**Comment by proteriax** [comment]
Published.
