### ISSUE TITLE
Subtle bug when looping static elements when using `htm` library

### ISSUE THREAD

**Issue by patdx** [proteriax/jsx-dom#32]
I was attempting to generate a list of repeating data using [htm](https://github.com/developit/htm) , and noticed a strange issue where some data was disappearing except for the last row. After some debugging, I discovered that it seems htm, because it using template strings, was caching the element and reusing it. So, as soon as it was attached to the DOM again, it moved from the original position to the new position.

Here is a small reproduction:

https://stackblitz.com/edit/js-gkm1bu?file=index.js

```js
import { createElement } from "jsx-dom";
import htm from "htm";

const html = htm.bind(createElement);

const appDiv = document.getElementById("app");

let count = 1;

// <div>cached static component</div>
// is totally static, so it seems to be cached by HTM. When we call appendChild a second time
// HTM provides the original instance from the
// cache and duplicates it.

function render() {
  appDiv.appendChild(
    html`
      <div>
        <div>Render ${count++}</div>
        <button onClick=${() => render()}>Render again</button>
        <div>cached static component</div>
      </div>
    `
  );
}

render();
```

Resolution:

I'm not sure if it is possible to fix this in code, so I would suggest just leaving some kind of documentation about this weird edge case for users of `htm`.

I think that regular JSX (NOT htm) would generally not have this issue, unless you set up some special optimization plugins like this: [babel-plugin-transform-react-constant-elements](https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements)?

**Comment by caph1993** [comment]
Indeed, htm has caching enabled by default 
It can be disabled in three simple ways, explained here: https://github.com/developit/htm#caching

One of them is to use "htm/mini" instead of "htm". The other could be to use a wrapper `function noCacheCreateElement(...args){this[0]=3; return createElement(...args);}`, though I haven't tested it.
