### ISSUE TITLE
Switching from addEventListener breaks custom events

### ISSUE THREAD

**Issue by kurtinatlanta** [proteriax/jsx-dom#33]
This PR - https://github.com/proteriax/jsx-dom/pull/17 - broke jsx-dom when using it with web components that use custom events. Those nodes will (may) not have functions attached to them for event handlers and need to use addEventListener.

Can this PR be reverted so that this library will work with web component tags?

**Comment by zenflow** [comment]
@kurtinatlanta That would break the use case described in the PR. Is there some way `jsx-dom` can support both use cases?

**Comment by kurtinatlanta** [comment]
What I did locally was to check for 'built-in' events (the on... function will be null instead of undefined) and set the property for those events but use addEventListener if the on... function in the node is undefined.

What complicates this is that the name of custom events appears to be case-sensitive so you have to listen for myEvent off of onMyEvent instead of myevent. I'm looking into that more to see if it's an issue all the time or just with the particular web component helper tool we use.

I have a code change that I can do as a PR once I test my theory.

**Comment by kurtinatlanta** [comment]
With custom events from a web component, node.onmyevent is never called like node.onclick.
