### ISSUE TITLE
issues with typings of svg elements

### ISSUE THREAD

**Issue by niklaspandersson** [proteriax/jsx-dom#34]
Amazing work! I've been trying to roll my own createElement/JSX suite, but this will save me weeks! 
Only two minor issues that is a bit of a pain right now.

The property `class?: ClassNames` is missing on interface `interface SVGAttributes<T>` in index.d.ts
It would also be great if `interface SVGProps<T>` could be exported so that i can declare typed vars to keep refs to svg elements.

Thanks for a great lib!

**Comment by proteriax** [comment]
This will be done by next release soon.
