### ISSUE TITLE
Build a UMD bundle for use in browser

### ISSUE THREAD

**Issue by gera2ld** [proteriax/jsx-dom#36]
Can you provide a bundle that can be used in browser directly? Maybe just replace the CJS bundle with a UMD one.

The use case is to create tracked DOM elements without introducing much overhead in simple scenarios. Sometimes compiling is too complex for a simple script to run in browser.

**Comment by proteriax** [comment]
https://wzrd.in/standalone/jsx-dom@latest

**Comment by zenflow** [comment]
Or https://bundle.run/jsx-dom@latest (uses Rollup instead of Browserify)

**Comment by maxchang3** [comment]
FYI, it seems that both `https://wzrd.in/standalone/jsx-dom@latest`[^1] and `https://bundle.run/jsx-dom@latest` are currently not accessible.

[^1]: https://github.com/browserify/wzrd.in/issues/209
