### ISSUE TITLE
Proposal: Change default value of FC's generic argument from Element to JSX.Element

### ISSUE THREAD

**Issue by Kir-Antipov** [proteriax/jsx-dom#42]
### Problem

Unfortunately, at the moment default values of `FC`'s generic arguments don't make any sense, cause without specifying them, the function returns `Element` by default, which is not valid `JSX.Element` since

```ts
type Element = ReactElement
type ReactElement = HTMLElement | SVGElement
```

Invalid code (that should not be invalid) example:

```tsx
import React, { FC } from "jsx-dom";

const Foo: FC = () => <div/>;
const element = <Foo/>;
```

Error message:

> TS2786: 'Foo' cannot be used as a JSX component.
  Its return type 'Element' is not a valid JSX element.
    Type 'Element' is missing the following properties from type 'SVGElement': ownerSVGElement, viewportElement, oncopy, oncut, and 90 more.

### Possible solution

Since returning a type from a function that is not considered a valid `JSX.Element` doesn't make sense (we simply cannot construct jsx with it), we can change `Element` to `JSX.Element`.

P.S. - I can include this fix in #40 if @proteriax agrees to apply the change

**Comment by proteriax** [comment]
I’m open to this. Does it break anything?

**Comment by Kir-Antipov** [comment]
@proteriax, I can't think of a scenario in which it would break something. At the moment `FC` without generic arguments doesn't work at all, so there's nothing to break, tbh :D

```diff
- interface FunctionComponent<P = {}, T extends Element = Element>
+ interface FunctionComponent<P = {}, T extends Element = JSX.Element>
```

This small change just makes it possible to use `FC` without specifying generic arguments, as is possible in React, and doesn't affect the existing code in any way

**Comment by proteriax** [comment]
Looks good. Do you want to make a pull request?

**Comment by Kir-Antipov** [comment]
Yep. I wanted to include this into existing #40, but you've already merged it :D So give me few more minutes
