### ISSUE TITLE
Question: should `class` and `className` properties be of the same type?

### ISSUE THREAD

**Issue by Kir-Antipov** [proteriax/jsx-dom#48]
At the moment `HTMLAttributes` and `SVGAttributes` definition looks like:

```ts
export interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
  // Extension
  class?: ClassNames

  // Standard HTML Attributes
  className?: string

  // ...
}
```
So `class` and `className` that refer to the same property have different types. And I don't know is it intentional or just copy-paste error since this approach has its own pros and cons.

Pros:
 - `ClassNames` is one of `jsx-dom`'s cool features which is not supported by React. So in case we want to port a component from `jsx-dom` to `React`, TypeScript will remind us that this functionality must be abandoned, since React components simply don't have a `class` property

Cons:
- Code looks inconsistent when using `className` and `class` simultaneously
- `ESLint + plugin:react/recommended` complains about `class` without this rule:
```json
"react/no-unknown-property": ["warn", { "ignore": ["class"] }] 
```

**Comment by proteriax** [comment]
They should be the same type. It’s an oversight on my part.

**Comment by Kir-Antipov** [comment]
@proteriax, ok, then I'll make PR to fix it tomorrow :)
