### ISSUE TITLE
Types: (Function component) cannot be used as a JSX component

### ISSUE THREAD

**Issue by fregante** [proteriax/jsx-dom#51]
_Reopening because the other issue went OT. Sorry about that_

```
error TS2786: 'TagIcon' cannot be used as a JSX component.
  Its return type 'ReactElement<any, any> | null' is not a valid JSX element.

147      <TagIcon/>
          ~~~~~~~
```

I'm using `@primer/octicons-react` and I'm aliasing `react` to `jsx-dom` in Webpack config, but TypeScript doesn't seem to automatically accept this:

```tsx
import React from 'jsx-dom';
import {TagIcon} from '@primer/octicons-react';

document.body.append(<TagIcon/>)
```

Unless I include this type in my global.d.ts:

```ts
declare module 'react' {
	const FC = (): JSX.Element => JSX.Element;
	const React = {FC};
	export default React;
}
```

**Question is:** Aren't these types automatically included in jsx-dom? If not, should they?

**Comment by proteriax** [comment]
I can’t include a declaration for React because there will be conflict for people who have both libraries installed.

**Comment by fregante** [comment]
Indeed, the main issue is that my suggestion doesn’t actually work out of the box and it requires aliasing `react` to `jsx-dom`. 

Once I have a better idea of how the library works on my codebase, perhaps I can document how to alias React components and make them work with typescript.
