### ISSUE TITLE
Add `"type": "module"` in package.json to enable loading in Node.js

### ISSUE THREAD

**Issue by silverwind** [proteriax/jsx-dom#57]
Would it be possible to add `"type": "module"` in `package.json`, enabling this module to be loaded in Node.js? Currently, I get this error when I try to import it:

```
$ node
Welcome to Node.js v15.12.0.
Type ".help" for more information.
> jsxDom = await import("jsx-dom")
(node:35343) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
node_modules/jsx-dom/index.js:477
export default index
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
```

I think there's no harm in adding this node-specific property and it would at least allow node to consume the module (for example, for server-side rendering).

**Comment by proteriax** [comment]
You can’t do server-side rendering since it relies on browser globals.

**Comment by silverwind** [comment]
> You can’t do server-side rendering since it relies on browser globals.

There are ways like https://github.com/jsdom/jsdom to simulate DOM APIs in Node, it's certainly possible.

As for me, I was primarily looking to inspect the module's exports in the Node REPL, which is currently not possible without this package.json change.

**Comment by proteriax** [comment]
You can now do that

**Comment by proteriax** [comment]
@silverwind Update: [`jsx-dom-cjs`](https://www.npmjs.com/package/jsx-dom-cjs) is now published.

**Comment by silverwind** [comment]
Working, thanks!

```js
> await import("jsx-dom")
[Module: null prototype] {
