### ISSUE TITLE
defaultProps for subchildren

### ISSUE THREAD

**Issue by adminy** [proteriax/jsx-dom#63]
I'm looking for something like connect which would pass down props to subcomponents.

like it could pass in some sort of state property to all the children of a component.

**Comment by proteriax** [comment]
Do you mean `Context`? Since `jsx-dom` renders child components directly to DOM nodes without `ReactDOM.render`, it’s impossible for a child component to access the state of a parent component, which will be evaluated after all child components are already converted to DOM nodes.

**Comment by adminy** [comment]
Ok, but a custom function component is part of jsx-dom. So there is a way to pass in arguments along with the tag ones right?

```
function CustomTag(props) {
   return <div>{state.page.name}</div>
}
<CustomTag />

// configure it for all jsx components
React.config.defaultParams = {state}

```

**Comment by proteriax** [comment]
You can already do that, see [README](https://github.com/proteriax/jsx-dom/blob/master/README.md?plain=1#L43).

**Comment by adminy** [comment]
Its not the same thing @proteriax. defaultProps can only be applied on individual components and the data usually comes from the instanced component meaning you have to mix definition and instanciation in the same place. Its very ugly and stupid.

Anyways thanks for your continuous support through this...
