### ISSUE TITLE
TS 4.4 undefined properties

### ISSUE THREAD

**Issue by KapitanOczywisty** [proteriax/jsx-dom#72]
Types needs update for [new strict option in TS4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes). This was already done in react types [DefinitelyTyped/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts)

**Comment by proteriax** [comment]
Can you point me to the commit of [DefinitelyTyped/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts) where they implemented it?

**Comment by KapitanOczywisty** [comment]
This was updated in bulk, but here is the commit: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d4f392fc96b00ee40ba76acfdc859890bb6b4272#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299

**Comment by proteriax** [comment]
Thanks, I’ll take a look

**Comment by KapitanOczywisty** [comment]
@proteriax When solving conflicts I found mistake in the commit:
https://github.com/proteriax/jsx-dom/commit/13bdbc9529ea800f08c0840879aca7a256f1a392#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR370-R371

**Comment by proteriax** [comment]
Thanks, fixed.
